### ISSUE TITLE
Webpack Error while loading assets

### ISSUE THREAD

**Issue by lejeremy** [rroylance/phaser-npm-webpack-typescript-starter-project#1]
Hi,

I made a fresh clone of your repo to give it a try. However I have the following error while running npm run server:dev

`ERROR in ./assets/atlases/preload_sprites_array.png
Module parse failed: e:\MyFolder\assets\atlases\preload_sprites_array.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src/assets.ts 30:65-116
 @ ./src/states/boot.ts
 @ ./src/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./src/app.ts`

My node version is v6.9.5 and I'm using windows 7

Any idea ?

**Comment by rroylance** [comment]
Hi, sorry you're having an issue.

I'm going to assume it's due to some incompatibility between at least one of the modules/plugins and node 6.9.5, I developed with 7.5.0 and after downgrading to 6.9.5 I see the same issue...

I'll can take a look tonight and see what I can do.

**Comment by lejeremy** [comment]
Thanks,

I have been browsing the web for similar issues but I didn't find anything  ...
My guess was something around file-loader ...

**Comment by ProfitWarning** [comment]
This will load assets
`{ test: /\.(jpg|png|xml|mp3|ogg|m4a|fnt|ac3)$/, loader: 'file-loader?name=assets/[hash].[ext]' },`

but example breaks with:
`ncaught TypeError: url.match is not a function
    at Phaser.Loader.transformUrl (game.js:72307)
    at Phaser.Loader.fileComplete (game.js:72934)
    at HTMLImageElement.file.data.onload (game.js:72452)`

**Comment by ProfitWarning** [comment]
It's a Windows thing.
change the file-loader test from `/assets\//`
to `/assets\\/`

Now it works.

**Comment by rroylance** [comment]
Awesome. Thanks @ProfitWarning and @lejeremy. I haven't had a chance to look at it the last couple days like I thought. I'll get that change in.

**Comment by lejeremy** [comment]
Now working like a charm. Thank you guys !
