### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by kolombet** [rroylance/phaser-npm-webpack-typescript-starter-project#11]
I can't see sourcemaps when debugging in chrome, only plain js. How to debug code with this template?

**Comment by Majirefy** [comment]
@kolombet 
This project doesn't have source map support now.
@rroylance Hope to add it!

**Comment by rroylance** [comment]
I'm looking into getting sourcemaps and possibly breakpoints working. Hopefully soon! Thanks.

**Comment by rroylance** [comment]
@kolombet @Majirefy I've been able to get it to source map to the individual files, however it maps to the compiled typescript, not the typescript itself... any idea how to get it to map to the typescript, I'm having no luck and searches isn't helping ? The compiled typescript is pretty close to the actual code, so it'd definitely be better than nothing if getting typescript mapping is not possible at the moment.

Let me know if you'd like the current mapping (to the compiled typescript) committed or if you'd rather wait for typescript mapping.

**Comment by Nepoxx** [comment]
What do you mean the compiled Typescript?

Ideally all you need is an inline-sourcemap in the bundled file.

**Comment by Nepoxx** [comment]
See https://github.com/rroylance/phaser-npm-webpack-typescript-starter-project/pull/18

The following are instructions to get this working with Visual Studio Code and Chrome. Tested and working on Arch Linux.

1. Install [Debugger For Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) in VSCode
2. Launch the dev server `npm run server:dev`
3. Launch VSCode's debugger
4. Enjoy!

Here is my `launch.json` file which launches a standalone chrome window:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:9000",
      "webRoot": "${workspaceRoot}",
      "userDataDir": "${workspaceRoot}/.vscode/chrome",
      "runtimeExecutable": "/usr/bin/google-chrome-stable"
    },
    {
      "type": "chrome",
      "request": "attach",
      "name": "Attach to Chrome",
      "port": 9222,
      "webRoot": "${workspaceRoot}"
    }
  ]
}
```

**Comment by rroylance** [comment]
By compiled TypeScript I mean the JS that gets generated. I only got it to show where the issue was in the JS that's generated, not the original TS. I'll merge your update in and see if that satisfies those that need it. Thanks.

**Comment by Nepoxx** [comment]
I'll test the workflow on Windows tomorrow and update the readme accordingly :)

**Comment by rroylance** [comment]
@Nepoxx Thanks for the help!
