### ISSUE TITLE
Help me with my project

### ISSUE THREAD

**Issue by Majirefy** [rroylance/phaser-npm-webpack-typescript-starter-project#12]
@rroylance Sorry to add another issue here, but I don't know other ways to contact you.

I made a template project from scratch with TypeScript, webpack, webpack dev server.
https://github.com/Majirefy/PhaserTest
I copied some configuration from your project. But now there are some problems.

Visual Studio Code failed to give me code completion.
It will say "cannot find Phaser" if you add codes in `app.ts` file.

Do you use VSC? How to config?

**Comment by rroylance** [comment]
@Majirefy I primarily use WebStorm, but do use VSCode every now and then. All you should need to do is add the phaser.comments.d.ts to your tsconfig (which you did); I pulled your project and Code Completion is working fine for me... and as expected removing phaser.comments.d.ts from tsconfig got rid of the completion. Not sure why you aren't getting it, probably just an indexing issue. Have you tried closing and reopening VSCode and/or rebooting your computer?

**Comment by Majirefy** [comment]
<img width="687" alt="2017-03-09 12 13 58" src="https://cloud.githubusercontent.com/assets/3023607/23712258/554286d8-045d-11e7-9ed6-6ad110389167.png">

Thanks! After restart VSC, it works.
What's more, when use tslint, it show some warning. How to fix it? (I don't want to change tslint rules for that:`"no-var-requires": true`)

**Comment by rroylance** [comment]
Not sure, I don't have that issue in my project; You must require the phaser libraries in your TS, so I feel like you're either stuck with the warning or have to change your lint rules. I may be wrong though, not sure.

**Comment by Majirefy** [comment]
Any other ways to require the Phaser libraries like import statement?

**Comment by rroylance** [comment]
I don't believe so, you could just add tslint:disable and tslint:enable comments before and after those 3 lines to get rid of the warning. Basically tells tslint "shut up, I know what I'm doing". Haha. https://palantir.github.io/tslint/usage/rule-flags/

**Comment by Majirefy** [comment]
@rroylance I found another template project on Phaser+webpack+TypeScript:
https://github.com/eduardonunesp/phaser-typescript-webpack-boilerplate

In this project's `webpack.config.js`, they put these js libraries, as a result, no need to put these in `app.ts` file.

```javascript
var path = require('path');

var webpack = require('webpack');

var HtmlWebpackPlugin = require('html-webpack-plugin');

var CopyWebpackPlugin = require('copy-webpack-plugin');



// Phaser webpack config

var phaserModule = path.join(__dirname, '/node_modules/phaser/');

var phaser = path.join(phaserModule, 'build/custom/phaser-split.js');

var pixi = path.join(phaserModule, 'build/custom/pixi.js');

var p2 = path.join(phaserModule, 'build/custom/p2.js');



module.exports = {

  entry: './src/index.ts',

  output: {

    pathInfo: true,

    filename: '[name].bundle.js',

    path: path.resolve('./dist'),

    publicPath: '/'

  },

  resolve: {

    extensions: ['', '.js', '.ts'],

  },

  plugins: [

    new CopyWebpackPlugin([

      {

        from: './src/assets',

        to:'./assets'

      }

    ]),

    new HtmlWebpackPlugin({

      template: './index.html',

      inject: 'body',

    }),

    new webpack.NoErrorsPlugin(),

  ],

  module: {

    loaders: [

      { test: /pixi\.js/, loader: 'expose?PIXI' },

      { test: /phaser-split\.js$/, loader: 'expose?Phaser' },

      { test: /p2\.js/, loader: 'expose?p2' },

      { test: /\.ts?$/, loader: 'ts', exclude: '/node_modules/' }

    ]

  },

  node: {

    fs: 'empty'

  },

  resolve: {

    alias: {

      'phaser': phaser,

      'pixi': pixi,

      'p2': p2,

    }

  },

  devtool: 'source-map'

}
```

**Comment by rroylance** [comment]
Cool. I'll look into expose loader and maybe switch mine to use it aswell. Thanks.

**Comment by Majirefy** [comment]
@rroylance You are always helpful!!! Thanks!

To be honest, through that way, I start to learn something about webpack.

BTW, how to access image files in `assets` folder? Or how to tell webpack to pack my `assets` folder?

**Comment by rroylance** [comment]
In my case, since I want everything in assets to be loaded by webpack I used a catch all rule in my webpack config; 

{test: /assets(\/|\\)/, loader: 'file-loader?name=assets/[hash].[ext]' }

This tells webpack to load and hash anything that is required within the assets directory. Then to actually have an asset included it has to be required (the reason that in my templates assets.ts all the asset paths are required and not just a path).

**Comment by Majirefy** [comment]
Any other ways?
If I don't generate `assets.ts` file, just use path in `load` function, how do I set in `webpack.config.js`?

**Comment by rroylance** [comment]
Just add the test, loader line in the last message to your webpack config and when you provide the path in the load function, just require it and it'll be handled by webpack. So you have something like;

game.load.image('image', require('assets/image.png');

**Comment by Majirefy** [comment]
@rroylance I tried to use expose loader in web pack 2 to remove `require()` from `app.ts` file, but failed. Any progress?

**Comment by rroylance** [comment]
@Majirefy Just pushed v1.7.6, which just makes use of expose-loader and changing the (global as any).whatever = require(...) to just be import '...' Does that solve your warning?

**Comment by Majirefy** [comment]
Yours project are no warning now.

For my project(I created the project for learning how to set up a web project like yours), it failed. Still report: ```Uncaught ReferenceError: PIXI is not defined```

https://github.com/Majirefy/PhaserTest
This is my project, don't forget to `nom install`.

**Comment by rroylance** [comment]
you need to switch your import order for PIXI and Phaser, Phaser needs PIXI to exist, so you need to import PIXI first; https://github.com/Majirefy/PhaserTest/blob/master/src/app.ts#L2-L3

**Comment by Majirefy** [comment]
Thanks!!!!

BTW, TSLint's recommend rules are really bad. It sorted my imports alphetabetizedly.

**Comment by rroylance** [comment]
FYI; I used Phaser's tsconfig with a couple minor tweaks (double to single quotes for example).

**Comment by Majirefy** [comment]
@rroylance Thanks a lot!

**Comment by Majirefy** [comment]
@rroylance Must I use file loader for assets?

I try to load images it failed.

**Comment by rroylance** [comment]
Failed how? And no, there are a few loaders; file-loader, url-loader, raw-loader, probably others, which you can then do other processing on using something like img-loader.

**Comment by Majirefy** [comment]
How to set up file loader for web pack?
I just add `{ test: /assets(\/|\\)/, loader: 'file-loader?name=assets/[hash].[ext]' },`to my webpack.dev.config.js, but how to use it in `boot.ts` state like load an image?


<img width="726" alt="2017-03-15 8 32 17" src="https://cloud.githubusercontent.com/assets/3023607/23948559/85d5b6e2-09be-11e7-9178-997ec97b0fc7.png">

**Comment by rroylance** [comment]
You need to npm install @types/node. Then you need to add "types": [ "node" ] to your tsconfig's compilerOptions.

**Comment by Majirefy** [comment]
Thanks!

**Comment by Majirefy** [comment]
I am now try to load custom local ttf font via WebFontLoader.

In my `app.ts`, I try to load:

```typescript
window.onload = () => {
    const gameWidth = 800;
    const gameHeight = 600;

    let gameConfig: Phaser.IGameConfig = {
        width: gameWidth,
        height: gameHeight,
        parent: "",
        renderer: Phaser.AUTO,
        resolution: 1,
    };

    let fontLoaderConfig: any = {};

    fontLoaderConfig.custom = {
        families: [],
        urls: [],
    };

    fontLoaderConfig.custom.families.push("songti");
    fontLoaderConfig.custom.urls.push(require("!file-loader?name=assets/fonts/[name].[ext]!assets/fonts/font.css"));

    fontLoaderConfig.active = () => {
        const game = new SimpleGame(gameConfig);
    };
    WebFontLoader.load(fontLoaderConfig);
};
```

But it still reported cannot find font.ttf file.

**Comment by rroylance** [comment]
You are not requiring your font.ttf, so it's not being included in the webpack build. You could either require it somewhere so it gets included or use something like https://github.com/kevlened/copy-webpack-plugin to just copy the files over.
