### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by Nepoxx** [rroylance/phaser-npm-webpack-typescript-starter-project#13]
Quick questions, where are the typescript definitions coming from? They're no working for me (`[ts] Cannot find name 'Phaser'`) and I can't find them on DefinitelyTyped. How do you make them work with this project?

**Comment by rroylance** [comment]
In the tsconfig I include the path to the phaser.comments.d.ts file in the phaser-ce node module folder. I would make sure you've npm installed, and restarted your editor. Failing that; what os, editor, etc. are you using?

**Comment by Nepoxx** [comment]
I've re-cloned from scratch and git-rebased my changes on it and I couldn't reproduce the issue. For what it's worth I'm using VSCode, the latest Node 6 (not on the said machine right now) on windows 10.

I'll investigate further tonight and figure out what caused it, thanks for the pointer!
