### ISSUE TITLE
How to load tilemap json?

### ISSUE THREAD

**Issue by Mirodil** [rroylance/phaser-npm-webpack-typescript-starter-project#16]
Hello,
Thank you for this starter project. 

How to load tilemap in json?

**Comment by rroylance** [comment]
Just drop your json in assets and then load it as usual; 

 game.load.tilemap(Assets.TilemapsTilemap.getName(), Assets.TilemapsTilemap.getJSON(), null, Phaser.Tilemap.TILED_JSON);

I'll add automatic loading in the next update. Thanks

**Comment by Mirodil** [comment]
thank you I've added some script to load it automatically?

**Comment by rroylance** [comment]
I'll add in the automatic loading, maybe tomorrow. Then you'll be able to skip this step altogether.
