### ISSUE TITLE
Dependency on git

### ISSUE THREAD

**Issue by Nepoxx** [rroylance/phaser-npm-webpack-typescript-starter-project#17]
This project assumes that it is running in a git folder, I'm looking for a suggestion on how to remove that.
Right now, in `webpack.dev.config.js` , replacing:

```javascript
'GIT_REVISION': '\"potato\"',
```

is a working workaround (the escaped quotes are required since the value is interpreted as-in (which seems bad)), but is hackish at best.

**Comment by rroylance** [comment]
You should just need to delete the GIT_REVISION part from define plugin (where you set it to potato, just delete that line) and then remove any occurence of GIT_REVISION from the code (I believe it's only used in one place in a console log). It doesn't actually require the use of hit or anything so you'll be fine to get rid of that.

**Comment by rroylance** [comment]
Considering this solved. Closing.
