### ISSUE TITLE
Local Font Support

### ISSUE THREAD

**Issue by Majirefy** [rroylance/phaser-npm-webpack-typescript-starter-project#2]
As for Chinese and Japanese languages, we should use a local font file(*.ttf file).

I am making a game with lots of dialogs, it will use many glyphs so bitmap is not suitable for Chinese.
Anyways to use local TTF fonts?

**Comment by rroylance** [comment]
At the current time, no, I'm just figuring out the best way to incorporate it with my no hassle assets thing I got going. I've also been busy the last week, so I haven't had a chance to look more at it. I'm hoping to have local don't support in sometime this week though...

**Comment by Majirefy** [comment]
@rroylance Thanks for your work!
This project is REALLY helpful!

**Comment by rroylance** [comment]
@Majirefy Support is in! Let me know if you run into any issues.

Really glad to hear that the project is helping someone 👍
