### ISSUE TITLE
Could not find linearInterpolation function in Phaser.Math

### ISSUE THREAD

**Issue by Mirodil** [rroylance/phaser-npm-webpack-typescript-starter-project#21]
if typing the bellow code:
```
game.math.linearInterpolation([1,2,3,4,5], 0.1);
```
the typescript throws error:
```
error TS2339: Property 'linearInterpolation' does not exist on type 'Math'.
```

**Comment by rroylance** [comment]
linearInterpolation is a static function of Phaser.Math, so it does not exists on a specific instance (game.math in your case). You just need to change it to;

`Phaser.Math.linearInterpolation([1,2,3,4,5], 0.1);`

and that should work.
