### ISSUE TITLE
How to build a custom Phaser

### ISSUE THREAD

**Issue by Nepoxx** [rroylance/phaser-npm-webpack-typescript-starter-project#23]
Is there a way to tell webpack to build a custom phaser? (as seen https://phaser.io/tutorials/creating-custom-phaser-builds )

**Comment by rroylance** [comment]
I'm not actually building phaser, I'm just using the prebuilt versions. Theoretically you should just need to build your own version, put the js file in some folder and change the phaser alias in the webpack configs to point to your version. Links below are for the dev config, just do the same for the dist config.

https://github.com/rroylance/phaser-npm-webpack-typescript-starter-project/blob/master/webpack.dev.config.js#L17 - Change this to point to your new js

https://github.com/rroylance/phaser-npm-webpack-typescript-starter-project/blob/master/webpack.dev.config.js#L68 - Change the regex to match the name of your new js

Again, this is theoretical, I haven't actually tried. If you try it out and it works, and if it doesn't, please let me know.

Thanks.
