### ISSUE TITLE
assetUtils.ts

### ISSUE THREAD

**Issue by chessIthaca** [rroylance/phaser-npm-webpack-typescript-starter-project#26]
Hi, 
added some text content and it seems that assetUtils. loadText is just not implemented correctly but rather a copy of loadXML.

I changed it to this but have not been able to verify it works as designed as I am fighting other errors.

```
private static loadText() {
        for (let text in Assets.Text) {
            if (!this.game.cache.checkTextKey(Assets.Text[text].getName())) {
                this.game.load.text(Assets.Text[text].getName(), Assets.Text[text], true);
            }
        }
    }
```

**Comment by chessIthaca** [comment]
replace Assets.Text[text] with Assets.Text[text].getTXT() and things seem right :)

**Comment by rroylance** [comment]
Whoops, my bad! Thanks again @chessIthaca!
