### ISSUE TITLE
Fail to change scale mode via "npm run setupGameSize"

### ISSUE THREAD

**Issue by Majirefy** [rroylance/phaser-npm-webpack-typescript-starter-project#3]
I want to change scale mode from default's "USER_SCALE" to "SHOW_ALL" by using command:

`npm run setupGameSize --width 800 --height 800 --scale-mode SHOW_ALL
`
But in game's console log:

```
DEBUG....................... true 
           
GIT_REVISION................ cc15ebdb3c91e11e0ebe53cec0454a8438a6ef58
           
SCALE_MODE.................. USER_SCALE
           
DEFAULT_GAME_WIDTH.......... 800
           
DEFAULT_GAME_HEIGHT......... 500
           
MAX_GAME_WIDTH.............. 888
           
MAX_GAME_HEIGHT............. 600 
           
game.width.................. 800 
           
game.height................. 580
           
GOOGLE_WEB_FONTS............ Barrio
           
SOUND_EXTENSIONS_PREFERENCE. webm,ogg,m4a,mp3,aac,ac3,caf,flac,mp4,wav
```

It's still USER_SCALE. Also, the game width and height are not changed.

**Comment by lejeremy** [comment]
You need to add '--' between arguments

Npm run setupGameSize -- --width 800 --height 800 --scale-mode SHOW_ALL
See commander documentation for more information

**Comment by Majirefy** [comment]
@lejeremy Thanks!!!

**Comment by rroylance** [comment]
@lejeremy Thanks for pointing that out! I've updated the README to show this requirement.
