### ISSUE TITLE
Is it possible to include plugins?

### ISSUE THREAD

**Issue by amenant** [rroylance/phaser-npm-webpack-typescript-starter-project#30]
Hello,
I'd like to add a plugin (https://github.com/lewster32/phaser-plugin-isometric) but can't make it work.
I'm not sure about how to do with the starter project. Any example?

Thanks.

**Comment by rroylance** [comment]
Hi, you should be able to just throw the js file into your assets folder and the game will automatically load it and the plugin will be available. You can then load and activate the plugin in your state's preload function, for example, using: `this.game.plugins.add(new Phaser.Plugin.Isometric(this.game));`

I haven't tried this exact plugin, but I can try it out this evening if you still can't get it going.

**Comment by amenant** [comment]
Hi,
that's what I did but I get an error.

assets.ts (generated)
```
export namespace Scripts {
    export class ScriptPhaserPluginIsometricMin {
        static getName(): string { return 'phaser-plugin-isometric-min'; }

        static getJS(): string { return require('assets/script/phaser-plugin-isometric-min.js'); }
    }
}
```

```
preload(): void {
    this.game.plugins.add(new Phaser.Plugin.Isometric(this.game));
}
```

[ts] Property 'Isometric' does not exist on type 'typeof Plugin'.

Do I need to make an import? The plugin also provide a .ts file, do I have to make use of it?

Thanks.

**Comment by rroylance** [comment]
Oh, right,  I never thought of needing the definitions for typescript when loading certain scripts... Oops. 

Yes, you'll need to include the d.ts file in your project (I usually have a folder called definitions in the root (not assets)), and then in the tsconfig.json you need to add the path to the d.ts file to the files array. 

That should tell typescript that the library exists and you should be good to go.

Thanks so much for bringing this to my attention, now I can add an additional tutorial or sorts to the readme :)

**Comment by amenant** [comment]
Thanks 👍
