### ISSUE TITLE
Spritesheet not generating

### ISSUE THREAD

**Issue by amenant** [rroylance/phaser-npm-webpack-typescript-starter-project#34]
Hello,
it seems it's not possible to generate spritesheets.
I dropped a file "file[10,10].png" in assets and a spritesheet is not generated.

Looking at the code, it seems this portion is looking at the file extension:
`var spritesheetData = gameAssets[i][0].match(/\[(-?[0-9],?)*]/);`

I don't feel familiar with this part, can you confirm there's a problem with this?

**Comment by SC0d3r** [comment]
Yeah there is a problem I just opened a pull request to fix that #36

**Comment by rroylance** [comment]
Merged in #36, give it a go now and update issue accordingly. Thanks!
