### ISSUE TITLE
What's "assets_raw"?

### ISSUE THREAD

**Issue by Majirefy** [rroylance/phaser-npm-webpack-typescript-starter-project#4]
What's "assets_raw" folder? Why we need it?

**Comment by rroylance** [comment]
assets_raw is the folder where I keep my assets before they are processed.

Things like my images and texture packer projects that export the spritesheets that go into assets. Or my tipemap project that exports the JSON to assets. Or all my audio before it's compiled into an audiosprite and put into assets. Etc...

You don't need it of you don't want it, I just use that style as my way of organizing my projects.

**Comment by Majirefy** [comment]
@rroylance 
Thanks for reply!

So this is just a temp folder? Files won't put into "assets" via `npm run assets`?

**Comment by rroylance** [comment]
Correct, It's just a development organizational folder more than anything.

I should probably add a note to the README about why that folder is there... Thanks.

**Comment by Majirefy** [comment]
@rroylance Thank you very much!!!!

**Comment by rroylance** [comment]
@Majirefy No problem! Anything else just let me know.
