### ISSUE TITLE
Asset Generation issues...

### ISSUE THREAD

**Issue by tomph** [rroylance/phaser-npm-webpack-typescript-starter-project#40]
I'm experiencing issues when building for dev/dist that are annoyingly happening only 90% of the time.  When asset generation is happening, quite often the compiler falls over with 100s of 

"ERROR in ./src/states/Instructions.ts
(25,86): error TS2339: Property 'BitmapFonts' does not exist on type 'typeof "C:/Users/XX/XX/XX/XX/src/assets"'.

It feels like the asset generation has not finished before it tries to compile the JS - meaning I get loads of errors of non-existent assets.  

I did try and add in the few lines from the latest merges, but it made no difference.

Any help would be great :)

**Comment by SC0d3r** [comment]
make sure to add two files with the same name but one .fnt ext and another with .png ext in assets/fonts
to create bitmapFonts 
and then run `$npm run assets` then go and check the **assets.ts** File, and see if  **namespace** BitmapFonts with **yourFontName** class is created or not if this is not your current problem take a screenshot of errors and post them

**Comment by rroylance** [comment]
#39 has been merged in with some asset generation fixes; please try the latest version out. Thanks!

**Comment by Nepoxx** [comment]
That did not fix the issue.

The issue stems from: https://github.com/1337programming/webpack-shell-plugin/issues/37

You can fix it by replacing 

```js
new WebpackShellPlugin({
  onBuildStart: ['npm run assets']
}),
```
with
```js
new WebpackSynchronizableShellPlugin({
  onBuildStart: {
    scripts: ['npm run assets'],
    blocking: true,
    parallel: false
  }
}),
```

in your webpack config (`npm isntall webpack-synchronizable-shell-plugin --save-dev` of course)

**Comment by rroylance** [comment]
@Nepoxx Huh, interesting, I've never encountered that one. Thanks so much for doing the research and providing the PR! Much appreciated 👍

**Comment by Nepoxx** [comment]
@rroylance I've never encountered the issue myself someone was not able to build our project due to this. Since it's a race condition it needs specific timings to occur, I think. In any case using WebpackSynchronizableShellPlugin should fix the issue :)

**Comment by rroylance** [comment]
Merged in. Thanks again @Nepoxx !
