### ISSUE TITLE
Corresponding File is Not Included In tsconfig.json

### ISSUE THREAD

**Issue by JimTheMan** [rroylance/phaser-npm-webpack-typescript-starter-project#42]
Hi, I just scaffolded this project. It compiiles, but I get a bnuch of errors in my IDE (webstorm) with squggly lines under the references to Phaser library. The error message is, "Corresponding File is Not Included In tsconfig.json".

**Comment by rroylance** [comment]
Phaser is in the tsconfig as "./node_modules/phaser-ce/typescript/phaser.comments.d.ts" under the files array, my best guess is that the IDE needs to finish indexing or maybe be updated and restarted (I use Webstorm as well and have no issues).

**Comment by KaplunMaxym** [comment]
If you use env vars in your file:

import process from 'node:process';
