### ISSUE TITLE
uglify error: Unexpected token: name (ImagesBackgroundTemplate)

### ISSUE THREAD

**Issue by ProfitWarning** [rroylance/phaser-npm-webpack-typescript-starter-project#43]
Hi,
I noticed that the latest version (master) has an error with `build:dist` .
Error: 
`ERROR in game.min.js from UglifyJs
Unexpected token: name (ImagesBackgroundTemplate) [game.min.js:88,10]`

Uglify can't parse es6 builds. 

I had to change the target in tsconfig.json to `es5` and include `lib: ["es2016", "dom"]`

here my tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": false,
    "experimentalDecorators": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "files": [
    "./src/globals.d.ts",
    "./src/app.ts",
    "./node_modules/phaser-ce/typescript/phaser.comments.d.ts"
  ]
}

**Comment by rroylance** [comment]
Merged #41 so this should be a non-issue now. Thanks!
