### ISSUE TITLE
Hacktoberfest 2017!

### ISSUE THREAD

**Issue by rroylance** [rroylance/phaser-npm-webpack-typescript-starter-project#44]
The annual [Hacktoberfest](https://hacktoberfest.digitalocean.com) is back! 

Please feel free to take a look at the issues already present or if you think of something else to contriute; whether it be a bug fix, new feature, optimization, or whatever else.

We'd love the help! Remember to have fun and get those 4 pull requests in by Halloween 🎃

**Comment by RaiVaibhav** [comment]
I am a bit confuse you said we have to make a pull request between 1 october and 31 october then what if anyone made a pull request and it gets merge???
Can you please elaborate

**Comment by rroylance** [comment]
Hi @RaiVaibhav!

The way Hacktoberfest works is that between now and October 31st if you make at least 4 pull requests on Open Source projects on GitHub [Digital Ocean](https://www.digitalocean.com/) will send you a free limited edition T-Shirt to commemorate Hacktoberfest.

Those 4 pull request do not have to be on the same project, they can be merged in or not; as long as you've opened them within the time limit it counts towards your goal.

**Comment by RaiVaibhav** [comment]
That means if someone makes a issue and label them with Hactoberfest and if i solved it then it will count my contribution to hacktoberfest??

**Comment by rroylance** [comment]
Any pull request, attached to a specific issue or not, will count (legitimate ones that is, any pull requests labeled as spam will get invalidated and the user possibly disqualified).

Some people add issues tagged with Hacktoberfest to draw attention to something specific they'd like worked on, some just do it as an announcement (like mine).

**Comment by RaiVaibhav** [comment]
Thanks
