### ISSUE TITLE
npm run server:dev fails

### ISSUE THREAD

**Issue by leozulfiu** [rroylance/phaser-npm-webpack-typescript-starter-project#51]
Hi

After installing all the dependencies I wanted to start the server but that didn't work. I'm getting some compilation errors and the opened tab stays blank:

https://gist.github.com/leozulfiu/e6ccf90b27122244ecaa2eaa3710b7c5

**Comment by rroylance** [comment]
Hmm. Looks like the assets.ts file failed to generate correctly...

What does your assets.ts look like and/or any errors you get when running ```npm run assets```?

**Comment by rroylance** [comment]
Sounds like this could be related to the issue shown in #40. Once @Nepoxx gets his PR up I'll merge it in and hopefully that will solve this issue as well.

**Comment by rroylance** [comment]
#55 merged in, from the sounds of it, that should solve your problem.
