### ISSUE TITLE
Classic Pong clone made easy with this project

### ISSUE THREAD

**Issue by ProfitWarning** [rroylance/phaser-npm-webpack-typescript-starter-project#52]
Hi,
I created a beginner level Pong clone with the help of this cool starter project.
Repo:
[https://github.com/ProfitWarning/p0ng](https://github.com/ProfitWarning/p0ng)

Live: 
[p0ng-live](http://pong.fastner-it.de/)

If you would like, you can add it to the list in readme.

best,
ProfitWarning

**Comment by rroylance** [comment]
Whoops, forgot to close this. Added your game a while ago. Thanks @ProfitWarning !
