### ISSUE TITLE
Suggestion for tslint.json

### ISSUE THREAD

**Issue by michelcve** [rroylance/phaser-npm-webpack-typescript-starter-project#54]
Just a suggestion for the tslint.json file.

I noticed that it's basically the same as phaser's own tslint, with the exception of one setting. You use single quotes instead of double.

You could simplify the tslint.json file to this (I also added a max-line-length option, which I think helps making code more readable), and automatically use the default phaser settings, and extending those for your own overrides:

```json
{
  "extends": "./node_modules/phaser-ce/typescript/tslint.json",
  "rules": {
    "quotemark": [
      true,
      "single"
    ],
    "max-line-length": [true, 140]
  }
}
```

**Comment by rroylance** [comment]
Good eye. Haha.

I like this. I will do that later today, or you can even create a pull request and I'll merge it I'm right away. Either way :relaxed:

**Comment by michelcve** [comment]
I'll let you do it, so you can decide on whether or not you want to add the 'the max-line-length' option ;-)
