### ISSUE TITLE
Working with loaded JSON

### ISSUE THREAD

**Issue by gilizeevi** [rroylance/phaser-npm-webpack-typescript-starter-project#56]
Hi, thanks for creating this Starter Project.

I'm having some trouble trying to use JSON files loaded with assetsUtils. Not sure If it's my lack of understanding or an actual issue.

When I add a JSON to the assets folder, I was assuming I could later access it through Assets.JSON.[name of json].getJSON(). In actuality getJSON() returns a path to the JSON (for example: "assets/0471943eb658d5fbb7f06bf1275a7fc7.json").

But how can I actually access the JSON contents?

**Comment by rroylance** [comment]
To load the JSON you need to access it via game.cache.getJSON(Assets.JSON.[name of json].getName()). Refer to http://phaser.io/examples/v2/loader/load-json-file

**Comment by gilizeevi** [comment]
Thank you @rroylance. 
The explanation clarified it for me.
