### ISSUE TITLE
npm install not installing dependencies

### ISSUE THREAD

**Issue by MorpheusZero** [rroylance/phaser-npm-webpack-typescript-starter-project#57]
Hey! Tried using this as an experimental test to see if I would go ahead and try using this instead of writing it all up myself--and I can't even get the dependencies to install. I tried installing that dependency below globally and it works--but I still get the below error regardless. Running Node_v8.4.0

I'm not sure if something with my environment is wonky--or if something is actually broken--but heads up regardless. I tried using the Bash terminal for npm install--also tried using Webstorm's built in support for installing the dependencies--as well as Atom's terminal. All the same.

What I am not actually understanding--is why npm is trying to resolve references in setupGameSize when all I want it to do is install deps?? Am I overlooking something?

![image](https://user-images.githubusercontent.com/5752785/34646378-b81903c8-f32b-11e7-973d-b60cac2df29a.png)

  UPDATE:

More information I have come across. I was able to get past the error above AFTER globally installing the dependency--then using an `npm link`

However, I had to do this for every single dependency in the package.json. I am unsure why. I am going to attempt to completely blow away and reinstall Node--but I can't imagine it would be causing problems because I use it for Angular Development on a daily basis.

**Comment by rroylance** [comment]
Hmm. That's a new one...  Ever had any issues with that. 

Sorry you're having so much trouble. At this point I can only assume that it's some oddity with your environment. But I'll try and do a fresh install tomorrow on my machine to make sure something isn't borked.

On your end, my first steps would be to uninstall and reinstall Node and doing a fresh clone of the project.

**Comment by rroylance** [comment]
@MorpheusZero Hmm. I do get this now... I just started a project a couple weeks ago and it was fine, so something must've changed in the last bit. Sorry for the delay, I have been really busy. I'll try and get that sorted ASAP.

**Comment by rroylance** [comment]
@MorpheusZero I still don't get why, but for now, if you just run `npm install pngjs-image` and then `npm install` it's all fine. Random issue... Hopefully, I can get that fixed today or tomorrow.

Thanks.

**Comment by rroylance** [comment]
@MorpheusZero Sorry for the spam of messages, but; I have found that the issue occurs when the dependencies added within devDependencies, and not dependencies. So I have updated the package.json to use dependencies instead and changed the tag for v1.8.4 to point to that commit.

Please try that out and let me know if it installs correctly. Sorry about that, that was weird. 

If you or anyone else can explain that one I'd love to know why it started happening.
