### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by taijeronv** [rroylance/phaser-npm-webpack-typescript-starter-project#58]
Richard,
Thank you for creating this Phaser template, especially the very detailed write up on its design/structure.  None of the other templates have that much detail.  Although I don't have any issues at the moment, I would like some advice.  Is TypeScript suitable for a beginner? I'll probably ask google but wanted to get your thoughts.

"If you use this template/starter project in any capacity; I’d love to hear about your experience with it. Whether you continued with it or decided not to (I really want to hear why you made your decision)."

- I love the detailed write up on the template especially since I'm a beginner.  I think it's important to know where to put things.  Other templates leave it up to the user to figure out.  If you're a beginner that can be challenging.
- I like the fact that it works.  I was able to install it without any issues from NPM.
- I like that you included Electron support.
- I like that you included links to three projects that use the template.

TJ

**Comment by rroylance** [comment]
Hi TJ,

Thanks for the feedback, I appreciate it. I'm glad to hear that I've presented it well and that it's working with no issues so far :) 

As for TypeScript being beginner friendly; I'd say definitely. It's got the ease of use and versatility of JavaScript but without all the terrible unfriendly and ugly things that come with it (no strong typing, no standard visibly identifiers, no somewhat standard looking classes (pre-es6 that is)) and many additional things that make working with JavaScript much nicer (take a look at the [TypeScript Handbook](http://www.typescriptlang.org/Handbook/), it's an excellent resource). I find TypeScript very pleasent to read and write and easily recommend it. 


I hope you make something I can add to the list in the README someday, please let me know! 

Thanks.
