### ISSUE TITLE
Unable to use plugins

### ISSUE THREAD

**Issue by tezqa** [rroylance/phaser-npm-webpack-typescript-starter-project#59]
I have followed the instructions in the README, but i have still the error:

`TS2694: Namespace 'Phaser.Plugin' has no exported member 'PhaserInput'.`

Here is what I did:
1. drop the plugin `PhaserInput.js` file into `assets/scripts` folder  (https://github.com/orange-games/phaser-input/blob/master/build/phaser-input.js)

2. declare the plugin in the assets.js file like this:
```
export namespace Scripts {
    export class ScriptsPhaserInput {
        static getName(): string { return 'PhaserInput'; }

        static getJS(): string { return require('assets/scripts/PhaserInput.js'); }
    }
}
```

3. create a 'definitions' folder in the project root and drop the d.ts file into (https://github.com/orange-games/phaser-input/blob/master/build/phaser-input.d.ts)

4. add the path to this file into the "files" array in the `tsconfig.json`file.

But when, in my state preload function, I declare `Phaser.Plugin.PhaserInput`, it doesn't work.

Am I missing something?

**Comment by rroylance** [comment]
Hi, sorry you're having issues.

From what I can tell PhaserInput is not defined as a property of Phaser.Plugin, it's just PhaserInput and is a subclass of Phaser.Plugin. So you should need to access it via the PhaserInput type, not Phaser.Plugins.PhaserInput.

Refer to it's README for the following getting started note ([here](https://github.com/orange-games/phaser-input#getting-started));

> After adding the script to the page you can activate it by enabling the plugin:
> `game.add.plugin(PhaserInput.Plugin);`

**Comment by tezqa** [comment]
Thanks, it works.

This plugin does not export anything, so i had to copy the js file locally to export PhaserPlugin.

And thanks for your awesome starter kit.

**Comment by rroylance** [comment]
Glad you got it working :)
