### ISSUE TITLE
Write files

### ISSUE THREAD

**Issue by tezqa** [rroylance/phaser-npm-webpack-typescript-starter-project#60]
Hi,

How to use the node fs module to write file when the game is running in Electron?

Thanks for your help!

**Comment by rroylance** [comment]
Hi @tezqa, I see no reason using fs as usual shouldn't work. (w3schools) [https://www.w3schools.com/nodejs/nodejs_filesystem.asphas] some good and easy to follow and try out examples.

**Comment by tezqa** [comment]
Hi @rroylance 

I had an error with webpack: `Module not found: Error: Cannot resolve module 'fs'`

But I solved by adding:
```
target: 'node',
```

But now I have a EACCESS error when trying to write my file.

**Comment by tezqa** [comment]
Ok forget it, it was because of the path i chose. Thanks :)

**Comment by tezqa** [comment]
I'm trying to access to Electron from the app code in order to get specifics user paths.

```
import { app } from 'electron'
app.getPath('documents')
```

But I got undefined when I try to import Electron. Any idea?

**Comment by rroylance** [comment]
Hi @tezqa, you may need to require electron rather than importing it. 

```
import app = require('electron'); // or something along these lines
```

**Comment by tezqa** [comment]
I have tried to use require and import, but without success...

`Error: Electron failed to install correctly, please delete node_modules/electron and try installing again`

It fails because of the `node_modules/electron/index.js` file:

```
var pathFile = path.join(__dirname, 'path.txt')

if (fs.existsSync(pathFile)) {
  module.exports = path.join(__dirname, fs.readFileSync(pathFile, 'utf-8'))
} else {
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
}
```

Indeed, __dirname is equal to `/` when the app is running.

**Comment by tezqa** [comment]
Ok I ended up with the Nodejs os module to find the correct path. I don't use Electron.
But it's strange that nobody here needs to use Electron within the app.

**Comment by rroylance** [comment]
Hmm. Glad you got it working home the less. Unfortunately I don't even use the electronic portion of this project at all so I'm pretty unfamiliar with it.
