### ISSUE TITLE
Auto-Resize Support?

### ISSUE THREAD

**Issue by bhEsquivel** [rroylance/phaser-npm-webpack-typescript-starter-project#62]
Does not respond to resizing of browser.

**Comment by rroylance** [comment]
You'll probably want to take a look at the [RESIZE SCALE_MODE](https://photonstorm.github.io/phaser-ce/Phaser.ScaleManager.html).

You can use the setupGameSize script to change the SCALE_MODE that'll be used. [README](README.md#change-the-game-size-and-generate-a-template-background )

**Comment by bhEsquivel** [comment]
@rroylance 
yeah thanks. RESIZE Scale mode is what Im looking.. Thanks
I just need to handle all my other UI to respond accordingly when screen size is changed.
