### ISSUE TITLE
Better dependency versions

### ISSUE THREAD

**Issue by joestrong** [rroylance/phaser-npm-webpack-typescript-starter-project#67]
All the dependency versions in package.json are too specific. We should change, for example `"phaser-ce": "2.11.1",` to `"phaser-ce": "^2.11.1",`

Keeping on fixed versions is bad, for example the electron version specified has security issues. The user can then use their own lock file for locking their versions.

**Comment by rroylance** [comment]
Finally got around to updating all dependencies, this has been fixed along with doing that. Thanks!
